### ISSUE TITLE
Spread is faster than Array.from

### ISSUE THREAD

**Issue by AjaxSolutions** [jotaijs/jotai-scope#14]
Minor improvement suggestion.

[Array.from vs Spread ](https://www.measurethat.net/Benchmarks/Show/1721/0/arrayfrom-vs-spread)

```
const isEqualSet = (a: Set<unknown>, b: Set<unknown>) =>
  a === b || (a.size === b.size && Array.from(a).every((v) => b.has(v)));
```

vs.

```
const isEqualSet = (a, b) =>
  a === b || (a.size === b.size && [...a].every(v => b.has(v)));
```

**Comment by dai-shi** [comment]
<img width="539" alt="image" src="https://github.com/jotaijs/jotai-scope/assets/490574/9555cf09-a66c-4342-932b-870344076901">

Array.from seems faster in my case.

**Comment by AjaxSolutions** [comment]
<img width="709" alt="Screenshot 2023-11-01 at 10 37 14 AM" src="https://github.com/jotaijs/jotai-scope/assets/397472/b2bad248-823c-44ee-a495-a46752c532d7">

Hmmm... this must be browser dependent.  I'm on an old iMac using the MS Edge browser., and spread is faster in my case.

**Comment by AjaxSolutions** [comment]
OK, I'll close this issue.
