### ISSUE TITLE
Can't use with reducer

### ISSUE THREAD

**Issue by ImSingee** [jotaijs/jotai-scope#16]
If used with reducer, the changes in the inner scope won't affect the outer.

Re-Produce: https://codesandbox.io/p/sandbox/zealous-framework-jnlrvf

(`Count` should be in sync, but not)

**Comment by dai-shi** [comment]
Thanks for reporting. Hmm, your code looks okay.
Are you sure if this issue is only with `atomWithReducer`? Using `atom` doesn't cause it?

**Comment by ImSingee** [comment]
@dai-shi Yes I’m sure there’s not problem with pure atom

**Comment by dai-shi** [comment]
@yf-yang do you notice something?

**Comment by dai-shi** [comment]
I actually don't understand where is the bug. It would be nice if we could find it. I hope to try it.

**Comment by dai-shi** [comment]
My hope was https://github.com/pmndrs/jotai/pull/2351 would fix completely, but there still seems to be an issue in jotai-scope.
