### ISSUE TITLE
Instance level debug flag for jotai-scope?

### ISSUE THREAD

**Issue by yf-yang** [jotaijs/jotai-scope#19]
Observability becomes an issue for jotai-scope, because with scoped atom, each atom will have multiple "instances" and JavaScript does not expose `id()` alike mechanism for distinguish instances of the same object.

Can we design an "instance level" debug flag for each scoped atom? That would help debugging.

**Comment by dai-shi** [comment]
Hi, thanks for opening an issue. Though, I'm not sure if I precisely understand the suggestion. Is it only about `jotai-scope`? Do "instances" mean the wrapped atoms?

**Comment by yf-yang** [comment]
Hmmm, when I start the issue, I mean the "scopedAtom" created in the ScopeProvider because it has the same debug label with the original one, so I cannot easily distinguish them. The `temp` property in this comment https://github.com/jotaijs/jotai-scope/issues/17#issuecomment-1897667703 is an example.

If I got it right, "wrapped atoms" means create an internal atom, then expose its derived atom to the global scope? It is already handled by debug label, right?

**Comment by dai-shi** [comment]
sorry i meant "scoped atoms".

I think I understand what you mean by instance-level debug flag.
