### ISSUE TITLE
how to get value of the different scope atom outside the scope

### ISSUE THREAD

**Issue by HananoshikaYomaru** [jotaijs/jotai-scope#23]
let say I am creating a list of of something. Each thing has a scope. In the parent I want to access all the atom value. 

is it possible? And if it is not, what do you recommend in that use case?

**Comment by yf-yang** [comment]
Sorry, I cannot get your point clearly. Would you like to share a simple example? You can use https://codesandbox.io/s/react-new as a starter.

Sounds like atoms in atom trick can work, but I still need clearer descriptions. The point is, **atom itself is a config that can be shared between components**.
References:
- https://jotai.org/docs/guides/composing-atoms
- https://jotai.org/docs/guides/atoms-in-atom
- https://jotai.org/docs/recipes/large-objects
