### ISSUE TITLE
expose context from create isolation

### ISSUE THREAD

**Issue by marcocondrache** [jotaijs/jotai-scope#26]
Because useStore by default uses the default context, when working in isolation, it's not possible to utilize hooks like useHydrateAtoms, as they all rely on useStore. Consequently, they would hydrate a different store from a different context.

I think it would be correct and beneficial either to directly export the context or to offer a custom useStore function, allowing other hooks to receive the store as an option.

I'm willing to submit a pull request if necessary.

**Comment by dai-shi** [comment]
Nice catch.

> to offer a custom useStore function

Let's do that. Yes, please open a PR.

**Comment by marcocondrache** [comment]
@dai-shi thank you. I've opened the PR.
