### ISSUE TITLE
Atom Families support - TypeError: fn is not a function (it is Object)

### ISSUE THREAD

**Issue by Tadimsky** [jotaijs/jotai-scope#52]
I'm getting an error when unmounting the `ScopeProvider` when just using atoms, and no atom families.

I think that the spreading of this set, when empty, is adding an object to the clean up functions which cannot be called:

https://github.com/jotaijs/jotai-scope/commit/a1d7c909c46322b90cfcda73b376022420022621#diff-d6a2b7535e5c937402c991bbcff9db5a2998ec232cf52500d35a2086289cc8d4R79-R82

![simulator_screenshot_573FAA27-FC4B-453C-92C6-1AE59CEF04E8](https://github.com/user-attachments/assets/2a4c3b44-95d5-40e0-bebc-800e3d60ac2a)

<img width="317" alt="image" src="https://github.com/user-attachments/assets/8413520a-f6e0-4998-894a-642b4123afd4">

**Comment by dmaskasky** [comment]
Could you share a codesandbox example of this issue?

**Comment by dmaskasky** [comment]
Resolved with https://github.com/jotaijs/jotai-scope/pull/55

Please update jotai-scope to 0.7.2.

**Comment by dmaskasky** [comment]
Resolved with https://github.com/jotaijs/jotai-scope/pull/55

Please update jotai-scope to [0.7.2](https://www.npmjs.com/package/jotai-scope/v/0.7.2).

**Comment by Tadimsky** [comment]
Amazing, thank you @dmaskasky - just updated and it's working now!
